alias copy="xclip -i -selection clipboard"
alias paste="xclip -o -selection clipboard"
alias hg="history | grep"
alias img="sxiv"
alias mvtransform="rename 'tr/ A-Z/_a-z/'"
alias emacs="emacsclient --alternate-editor='' --no-wait"
alias emact="emacsclient -t --alternate-editor=''"
alias emacs-new="emacsclient -c -n"
alias aptudg="sudo apt update && sudo apt upgrade"
