#!/bin/bash

save()
{
    echo "Saving files"
    mkdir -pv config
    mkdir -pv bin

    # Copy config files into config dir
    cp -v ~/.tmux.conf config/tmux.conf
    cp -v ~/.vimrc config/vimrc
    cp -v ~/.xbindkeysrc config/xbindkeysrc

    # Copy bin files into bin dir
    cp -rv ~/bin/ ./
}

load()
{
    echo "Loading files"
    mkdir -pv ~/bin

    # Copy config files from config dir
    cp -v config/tmux.conf ~/.tmux.conf
    cp -v config/vimrc ~/.vimrc
    cp -v config/xbindkeysrc ~/.xbindkeysrc

    # Copy bin files from bin dir
    cp -rv bin/ ~/
}

init()
{
    echo "Initialising..."

    echo "Installing programs"
    sudo apt update
    sudo apt install -y tmux firefox keepassx mpv vim fish virtualbox xbindkeys git rofi

    echo "Setting git email"
    git config --global user.email "leslie.hor@gmail.com"

    echo "Setting git username"
    git config --global user.name "leslie"

    echo "Setting fish as default shell"
    chsh -s `which fish`

    echo "Installing oh-my-fish"
    curl -L https://get.oh-my.fish | fish

    echo "Installing anf setting beloglasov theme in fish"
    echo "omf install beloglazov | fish"
    echo "omf theme beloglazov | fish"

    echo "Loading config and bin files"

    load
}

case $1 in
save)
    save
    ;;
load)
    load
    ;;
init)
    init
    ;;
*)
    echo "What?"
    ;;
esac
