#!/bin/bash

save_config()
{
    echo "Saving files"
    mkdir -pv config
    mkdir -pv bin

    # Copy config files into config dir
    cp -v ~/.tmux.conf config/tmux.conf
    cp -v ~/.vimrc config/vimrc
    cp -v ~/.xbindkeysrc config/xbindkeysrc
    cp -v ~/.bash_prompt config/bash_prompt
    cp -v ~/.bash_aliases config/bash_aliases

    # Copy bin files into bin dir
    cp -rv ~/bin/ ./
}

install_config()
{
    echo "Loading files"
    mkdir -pv ~/bin

    # Copy config files from config dir
    cp -v config/tmux.conf ~/.tmux.conf
    cp -v config/vimrc ~/.vimrc
    cp -v config/xbindkeysrc ~/.xbindkeysrc
    cp -v config/bash_prompt ~/.bash_prompt
    cp -v config/bash_aliases config/bash_aliases

    # Copy bin files from bin dir
    cp -rv bin/ ~/
}

init_config()
{
    echo "Initialising..."

    echo "Installing programs"
    sudo apt update
    sudo apt install -y tmux firefox keepassx mpv vim virtualbox xbindkeys git rofi wmctrl

    echo "Setting git email"
    git config --global user.email "leslie.hor@gmail.com"

    echo "Setting git username"
    git config --global user.name "leslie"

    echo "Loading config and bin files"
    install_config
}

github_mirror()
{
    echo "Sending to Github"

    # Things to copy
    cp ./config/tmux.conf ~/Git/github-dotfiles/config/tmux.conf
    cp ./config/vimrc ~/Git/github-dotfiles/config/vimrc
    cp ./config/xbindkeysrc ~/Git/github-dotfiles/config/xbindkeysrc
    cp ./config/bash_prompt ~/Git/github-dotfiles/config/bash_prompt
    cp ./config/bash_aliases ~/Git/github-dotfiles-config/bash_prompt

    cp ./bin/connect ~/Git/github-dotfiles/bin/connect
    cp ./bin/rpn ~/Git/github-dotfiles/bin/rpn

    cd ~/Git/github-dotfiles/
    git add .
    git commit -m "Update Github repo"
    git push
}

case $1 in
save-config)
    save_config
    ;;
install-config)
    install_config
    ;;
init-config)
    init_config
    ;;
github-mirror)
    github_mirror
    ;;
*)
    echo "dotfiles"
    echo "    save-config - Copy the currently installed dot files into this project"
    echo "    install-config - Copy the project dot files into the system locations"
    echo "    init-config - Install and initialise a new system"
    echo "    github-mirror - Copy this repo to Github"
    ;;
esac
