#!/bin/bash

save_config()
{
    echo "Saving files"
    mkdir -pv config
    mkdir -pv bin

    # Copy config files into config dir
    cp -v ~/.tmux.conf config/tmux.conf
    cp -v ~/.vimrc config/vimrc
    cp -v ~/.xbindkeysrc config/xbindkeysrc

    # Copy bin files into bin dir
    cp -rv ~/bin/ ./
}

install_config()
{
    echo "Loading files"
    mkdir -pv ~/bin

    # Copy config files from config dir
    cp -v config/tmux.conf ~/.tmux.conf
    cp -v config/vimrc ~/.vimrc
    cp -v config/xbindkeysrc ~/.xbindkeysrc

    # Copy bin files from bin dir
    cp -rv bin/ ~/
}

init_config()
{
    echo "Initialising..."

    echo "Installing programs"
    sudo apt update
    sudo apt install -y tmux firefox keepassx mpv vim fish virtualbox xbindkeys git rofi wmctrl

    echo "Setting git email"
    git config --global user.email "leslie.hor@gmail.com"

    echo "Setting git username"
    git config --global user.name "leslie"

    echo "Setting fish as default shell"
    chsh -s `which fish`

    echo "Installing oh-my-fish"
    curl -L https://get.oh-my.fish | fish

    echo "Installing anf setting beloglasov theme in fish"
    echo "omf install beloglazov | fish"
    echo "omf theme beloglazov | fish"

    echo "Loading config and bin files"

    load
}

github_mirror()
{
    echo "Sending to Github"

    cp ./* ~/Git/github-dotfiles/
    cd ~/Git/github-dotfiles/
    git add .
    git commit -m "Update Github repo"
    git push
}

case $1 in
save-config)
    save_config
    ;;
install-config)
    install_config
    ;;
init-config)
    init_config
    ;;
github-mirror)
    github_mirror
    ;;
*)
    echo "dotfiles"
    echo "    save-config - Copy the currently installed dot files into this project"
    echo "    install-config - Copy the project dot files into the system locations"
    echo "    init-config - Install and initialise a new system"
    echo "    github-mirror - Copy this repo to Github"
    ;;
esac
