#!/bin/bash

if [ -z ${1} ] ; then
    echo "Need a config file, moron"
    exit 1
fi

dir=$(echo "data/${1}")

echo "Directory: ${dir}"

while read line; do
    loc=$(eval echo ${line} | sed 's/ .*//')
    rem=$(eval echo ${line} | sed 's/.* //')
    if [ -z ${loc} ] ; then
        exit 1 
    fi
    
    echo "Copying ${dir}/${rem} to ${loc}"
    
    cp ${dir}/${rem} ${loc}
done <${1}
