* dotfiles

** Install
Install the following packages:

#+BEGIN_SRC sh
stow -nSv <VERSION> -t ~
stow -Sv <VERSION> -t ~
#+END_SRC

** TODO Uninstall
#+BEGIN_SRC sh
stow -nDv <VERSION> -t ~
stow -Dv <VERSION> -t ~
#+END_SRC


** Files
*** =.bashrc=
*** =.bash_aliases=
*** =.keynavrc=
*** =.tmux.conf=
*** =.bash_prompt=
*** =.tridactylrc=
*** =.stalonetrayrc=
*** =.config=
**** =i3status=
***** =dzen2_bar=
The =dzen2= bar depends on =i3c= to detect displays and add a dock to each display.
***** =run_dzen2_bar=
**** =dunst=
***** =dunstrc=
**** =i3=
***** =i3c=
The =i3c= python script offers some functionality that is missing from =i3=.

Compatible with =i3wm= versions:
- 4.12 ([[https://github.com/i3/i3/blob/c9f0bc174d0746c925443d49bcc07727b631e335/docs/userguide][User guide]])
- 4.14.1 ([[https://github.com/i3/i3/blob/83a62267dce22d5d898d861bc957a6266268d030/docs/userguide][User guide]])

=i3= v4.12 lacks the =swap= command, so marks are used to facilitate.

***** =config=
***** =keybind_popup=
***** =mini_popup=
*** =bin=
**** =set-cpu-max=
**** =brightness-up=
**** =org-clip=
**** =passmenu=
**** =brightness-down=
**** =toggle-sticky-keys=
**** =toggle-mute=

** Firefox
Unfortunately, =firefox= uses unique ids for profile names, which I am unable to handle using stow.

Sym link the following:

#+BEGIN_SRC
firefox/userChrome.css --> ~/.mozilla/firefox/<ID>.default/chrome/userChrome.css
firefox/userContent.css --> ~/.mozilla/firefox/<ID>.default/chrome/userContent.css
#+END_SRC

You may need to create parent directories.

These files disable the tab bar, and set the default background to grey so you
don't get flashed with a white screen when a page is loading.

Note the css that hides the tab bar. I do not use tabs in firefox. Instead, I
use =i3='s tab layout to achieve the same thing but with better integration with
the wm. This has the advantage of being able to use the same commands to move
tabs around my desktop as moving normal windows. E.g. I can yank a tab and paste
it to a different workspace whilst leaving all other tabs alone, or use the
window search to also find browser tabs.

*** =about:config= settings

| Setting                                             | Value |
|-----------------------------------------------------+-------|
| =toolkit.legacyUserProfileCustomizations.stylesheets= | =true=  |
| =browser.tabs.opentabfor.middleclick=                 | =false= |
| =layout.css.devPixelsPerPx=                           | =0.70=  |
| =browser.fixup.alternative.enabled=                   | =false= |
| =browser.urlbar.trimURLs=                             | =false= |
| =browser.zoom.siteSpecific=                           | =false= |

*** Addons
- Ublock origin
- Dark Background and Light Text
- Imagus
- SingleFile
- Tridactyl
- Disable Autoplay for Youtube
- Stylus
- Video Speed Controller
- Youtube Classic
