#!/bin/bash

if [ -z ${1} ] ; then
    echo "Need a config file, idiot"
    exit 1
fi

name=$(echo "$1" | sed 's/config\///')
dir=$(echo "data/${name}")
mkdir -p ${dir}

echo "Directory: ${dir}"

while read line; do
    loc=$(eval echo ${line} | sed 's/ .*//')
    rem=$(eval echo ${line} | sed 's/.* //')
    if [ -z ${loc} ] ; then
        exit 1 
    fi
    
    echo "Copying ${loc} to ${dir}/${rem}"
    
    cp ${loc} ${dir}/${rem}
done <${1}
