#!/bin/bash

dir=$(echo ${1} | sed 's/\.config//')
mkdir -p ${dir}

echo "Directory: ${dir}"

while read line; do
    loc=$(echo ${line} | sed 's/ .*//')
    rem=$(echo ${line} | sed 's/.* //')
    if [ -z ${loc} ] ; then
        exit 1 
    fi
    
    echo "Copying ${loc} to ${dir}/${rem}"
    
    cp ${loc} ${dir}/${rem}
done <${1}
