#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# TODO: Kde is managing this now
xsetroot -solid '#5A8E3A'
# feh --bg-fill --no-xinerama IMGFILE
# feh --bg-fill IMG1 IMG2 IMG3

# keybindings
~/.config/herbstluftwm/keybindings

# tags
# default_num_of_tags=3
hc rename default "1" || true
# num_of_tags=$(hc tag_status | awk '{print NF}')

# if [ ${num_of_tags} -lt ${default_num_of_tags} ]; then
#     for i in $(seq $(echo "${num_of_tags} + 1" | bc) ${default_num_of_tags}); do
#         hc add ${i}
#     done
# fi

# Until I can figure out why the above code isn't working
# I am forcing four tags to be generated so herbstluft can
# detect the monitors and apply tags to each one
hc add 1 || true
hc add 2 || true
hc add 3 || true
hc add 4 || true

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1

# Layout Algorithms
#
# 0: vertical - clients are placed below each other
# 1: horizontal - clients are placed next to each other
# 2: max - all clients are maximized in this frame
# 3: grid - clients are arranged in an almost quadratic grid
hc set default_frame_layout 3 # Set default tiling to grid
hc set swap_monitors_to_get_tag 0

hc set  frame_bg_normal_color     '#888888' # Inactive empty frame colour
hc set  frame_bg_active_color     '#55FF55' # Active empty frame colour

hc set  frame_border_normal_color '#555555' # Outer inactive colour
hc attr theme.normal.color        '#555555' # Real inactive colour

hc set  frame_border_active_color '#555555' # Outer active colour
hc attr theme.active.color        '#55FF55' # Main active colour
hc attr theme.active.inner_color  '#55FF55' # Inner active colour

hc attr theme.active.outer_color  '#FFFFFF' # ????
hc attr theme.background_color    '#FFFFFF' # ????

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# Rules so KDE doesn't make hlwm freak out
hc rule class=plasmashell manage=off
hc rule class=krunner manage=off
hc rule class=Plasma manage=off
hc rule class=plasma-desktop manage=off
hc rule class=win7 manage=off
hc rule class=Kmix manage=off
hc rule class=Klipper manage=off
hc rule class=Plasmoidviewer manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors
hc detect_monitors

# Hacky way to start kde properly
# This ensures hlwm will apply the rules to kde applications
killall plasmashell
plasmashell &

# find the panel
#panel=~/.config/herbstluftwm/panel.sh
if [ -x "$panel" ] ; then
    "${panel}" &
else # Default
    #panel=/etc/xdg/herbstluftwm/panel.sh
    panel=~/.config/herbstluftwm/panel.sh
    for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
        # start it on each monitor
        "$panel" $monitor &
    done
fi
