#!/usr/bin/env bash

PID_FILE="${HOME}/.config/herbstluftwm/which-key.pid"
KEYBINDINGS="${HOME}/.config/herbstluftwm/keybindings"

if [ -f ${PID_FILE} ]; then
    PARENT_PID=$(cat ${PID_FILE}) || true
    CHILD_PID=$(pgrep -P ${PARENT_PID}) || true
    kill ${PARENT_PID} || true
    kill ${CHILD_PID} || true
    rm ${PID_FILE}
fi

if [ ${1} != "default" ]; then
    TABLE=${1}
else
    echo "default" | dzen2 -p 1\
                           -w '100' \
                           -x '2830' \
                           -e 'onstart=uncollapse' \
                           -fn '-*-fixed-medium-*-*-*-12-*-*-*-*-*-*-*' \
                           -fg '#efefef' \
                           -bg '#101010'
    exit 0
fi

echo $$ > ${PID_FILE}

sleep 0.5

HELP=$(sed -ne "/^${TABLE}() {/,/^}/p" "${KEYBINDINGS}" \
           | grep -v 'hc keybind Escape' \
           | grep 'hc keybind' \
           | grep -oP 'hc keybind \K.*' \
           | sed 's/^\([A-Za-z0-9]*\).*# \(.*\)/\1 : \2/' \
           | sed 's/^\([A-Za-z0-9]*\) $set_keys \(.*\)/\1 : -> \2/')

TEXT="${TABLE}"
HELP=$(printf "${HELP}\n" | column -c 100 -x | expand | sed 's/^/ /')
TEXT="${TEXT}\n\n${HELP}\n"

printf "${TEXT}" | dzen2 -p \
                         -w '800' \
                         -x '2480' \
                         -e 'onstart=uncollapse' \
                         -l $(printf "${TEXT}" | wc -l) \
                         -fn '-*-fixed-medium-*-*-*-12-*-*-*-*-*-*-*' \
                         -fg '#efefef' \
                         -bg '#101010'
