#!/usr/bin/env bash

MINI_POPUP=~/.config/i3/mini_popup

if [ "${1}" == "window" ]; then
    TITLE="window"
    TEXT="h - split right
v - split vertical
u - focus parent
d - focus child
m - toggle fullscreen
f - toggle floating"

elif [ "${1}" == "buffer" ]; then
    TITLE="buffer"
    TEXT="y - buffer yank
p - buffer paste
j - jump to window
b - bring window"

elif [ "${1}" == "frame" ]; then
    TITLE="frame"
    TEXT="r - rename workspace
c - create new workspace"

elif [ "${1}" == "applications" ]; then
    TITLE="applications"
    TEXT="o - open application
f - firefox
e - emacs
t - thunderbird"

fi

${MINI_POPUP} "${TITLE}" "${TEXT}"
