#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

CURRENT_INDEX=1
for TAG in $(hc tag_status); do
    TAG_NAME=${TAG:1}
    if [[ ${TAG_NAME} =~ ^[0-9]+$ ]]; then
        hc rename ${TAG_NAME} ${CURRENT_INDEX}
    fi
    CURRENT_INDEX=$((CURRENT_INDEX + 1))
done
