#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

FOCUSED_TAG=$(hc tag_status | grep -oP '\#\K([A-Za-z0-9_-]*)') || exit 1
NEW_NAME=$(echo -n | dmenu -p "Rename")

hc rename ${FOCUSED_TAG} ${NEW_NAME}
