#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

window_id_title_list() {
    wmctrl -l | awk '{printf $1" : "; for(i=4;i<=NF;i++)printf $i" "; print""}'
}

window_id=$(window_id_title_list | dmenu -i -p "Bring" -l 10 | sed 's/^\(.*\) .*/\1/')

hc bring ${window_id}
