alias copy="xclip -i -selection clipboard"
alias payst="xclip -o -selection clipboard"
alias hg="history | grep"
alias img="sxiv"
alias emacs="emacsclient --alternate-editor='' --no-wait"
alias emact="emacsclient -t --alternate-editor=''"
alias emacs-new="emacsclient -c -n"
alias flush-caches="systemd-resolve --flush-caches ; systemd-resolve --statistics"
