#!/usr/bin/python

import sys
import math

STACK = []

def main():
    Operators = sys.argv[1:]

    if len(Operators) == 1:
        Operators = Operators[0].split(" ")

    stack_process(Operators)

def stack_process(Operators):
    global STACK
    while len(Operators) > 0:
        # Pop off the first element
        Operator = Operators[0]
        Operators = Operators[1:]

        process(Operator)

    if len(STACK) == 1:
        STACK = STACK[0]

    print STACK

def process(Operator):
    global STACK
    # First, check if it is a number
    try:
        Num = float(Operator)
        push(Num)
        return
    except:
        None

    # Otherwise, try and process the operator
    if Operator == "+":
        X = pop()
        Y = pop()
        push(X + Y)
    elif Operator == "-":
        X = pop()
        Y = pop()
        push(Y - X)
    elif Operator == "x" or Operator == "*":
        X = pop()
        Y = pop()
        push(X * Y)
    elif Operator == "/":
        X = pop()
        Y = pop()
        push(Y / X)
    elif Operator == "pi":
        push(math.pi)
    elif Operator == "^":
        X = pop()
        Y = pop()
        push(Y ** X)
    elif Operator == "sum":
        STACK = [sum(STACK)]
    elif Operator == "swap":
        X = pop()
        Y = pop()
        push(X)
        push(Y)


def pop():
    global STACK
    X = STACK[len(STACK) - 1]
    STACK = STACK[:len(STACK) - 1]
    return X

def push(X):
    global STACK
    STACK.append(X)

if __name__ == '__main__':
    main()