#!/usr/bin/env bash

i3c="${HOME}/.config/i3/i3c"

PID_FILE="${HOME}/.config/i3/mini_popup.pid"

if [ -f ${PID_FILE} ]; then
    PARENT_PID=$(cat ${PID_FILE}) || true
    CHILD_PID=$(pgrep -P ${PARENT_PID}) || true
    kill ${PARENT_PID} || true
    kill ${CHILD_PID} || true
    rm ${PID_FILE}
fi

FONT="$(xrdb-query 'Leslie.bar.font')"
FG='#FFFFFF'
BG='#222222'
LINES=$(( $(printf "${@}\n" | wc -l) - 1 ))

ACTIVE_DISPLAY=$(${i3c} active-display)
X=$(${i3c} dzen2-bar-x ${ACTIVE_DISPLAY})
WIDTH=$(${i3c} dzen2-bar-width ${ACTIVE_DISPLAY})
FONT_WIDTH=$(( ${WIDTH} / $(dzen2-textwidth ${FONT} ".") - 1 ))

printf "${@}\n" | dzen2 -p 5 \
                        -e 'onstart=uncollapse' \
                        -l ${LINES} \
                        -w ${WIDTH} \
                        -x ${X} \
                        -fn ${FONT} \
                        -fg ${FG} \
                        -bg ${BG} \
